spring.application.name=ucc-orientacion-backend

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ucc_orientacion}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:proyecto}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

jwt.secret=${JWT_SECRET:ucc_orientacion_jwt_secret_2026_spring}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

app.institutional-email-domains=${INSTITUTIONAL_EMAIL_DOMAINS:campusucc.edu.co,ucc.edu.co}

spring.threads.virtual.enabled=true

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
